#app-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  SQL_USER: ZGJ1c2Vy          # "dbuser"
  SQL_PASSWORD: ZGJwYXNz      # "dbpass"
  #Base64 value for Django SECRET_KEY
  SECRET_KEY: ZGphbmdvLWluc2VjdXJlLXNtZHdqNyh0dWZeYioudDZnamYjdi5pKHBjXzgmaXl5dz02XmFoMyYqQGEsNCklJiBlK3ps

