#app-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: staticfiles
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-client