#app-service.yaml
apiVersion: v1
kind: Service
metadata:
  # nginx configmap upstream'u servis adı "app"ı bekliyor
  name: app
spec:
  selector:
    app: app
  ports:
  - port: 8000
    targetPort: 8000