#argocd.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: django-argo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/selimatmaca/website-deploy.git
    targetRevision: HEAD
    path: . 
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true

