apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -dev
namespace: default
resources:
  - ../../base
images:
  - name: selimica/website-app
    newName: selimica/website-app
    newTag: "latest"   # veya Jenkins build numarası
