apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: website
  annotations:
    # HTTP , HAProxy 80->Ingress works
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - host: website.configland.com    # own host
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: website
            port:
              number: 80
