apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: selimica/website-app
    newName: selimica/website-app
    newTag: "0.0.0"   # Jenkins will update here
